/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    './app/**/*.{ts,tsx,js,jsx}',
    './components/**/*.{ts,tsx,js,jsx}',
    './features/**/*.{ts,tsx,js,jsx}',
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#3f465c",
        "on-tertiary-fixed": "#001a42",
        "inverse-on-surface": "#eff1f3",
        "on-primary-fixed": "#131b2e",
        "primary": "#000000",
        "error": "#ba1a1a",
        "on-background": "#191c1e",
        "inverse-primary": "#bec6e0",
        "on-secondary-container": "#57657b",
        "surface-container-low": "#f2f4f6",
        "on-tertiary-fixed-variant": "#004395",
        "surface": "#f7f9fb",
        "primary-fixed-dim": "#bec6e0",
        "surface-variant": "#e0e3e5",
        "on-primary-container": "#7c839b",
        "surface-dim": "#d8dadc",
        "on-tertiary-container": "#3980f4",
        "surface-container": "#eceef0",
        "surface-tint": "#565e74",
        "secondary-container": "#d5e3fd",
        "on-secondary-fixed-variant": "#3a485c",
        "secondary-fixed": "#d5e3fd",
        "primary-fixed": "#dae2fd",
        "secondary": "#515f74",
        "tertiary-fixed-dim": "#adc6ff",
        "on-primary": "#ffffff",
        "on-surface-variant": "#45464d",
        "tertiary-container": "#001a42",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#0d1c2f",
        "tertiary-fixed": "#d8e2ff",
        "background": "#f7f9fb",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#b9c7e0",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#e0e3e5",
        "on-surface": "#191c1e",
        "surface-container-high": "#e6e8ea",
        "surface-bright": "#f7f9fb",
        "tertiary": "#000000",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#131b2e",
        "outline-variant": "#c6c6cd",
        "inverse-surface": "#2d3133",
        "outline": "#76777d"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "gutter": "16px",
        "toolbar-height": "64px",
        "sidebar-width": "260px",
        "container-padding": "24px",
        "unit": "4px"
      },
      fontFamily: {
        "body-md": ["Inter"],
        "h1": ["IBM Plex Sans"],
        "h3": ["IBM Plex Sans"],
        "body-lg": ["Inter"],
        "label-caps": ["Inter"],
        "h2": ["IBM Plex Sans"],
        "body-sm": ["Inter"],
        "data-tabular": ["JetBrains Mono"]
      },
      fontSize: {
        "body-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0", "fontWeight": "400" }],
        "h1": ["30px", { "lineHeight": "38px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "h3": ["20px", { "lineHeight": "28px", "letterSpacing": "0", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "24px", "letterSpacing": "0", "fontWeight": "400" }],
        "label-caps": ["11px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700" }],
        "h2": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-sm": ["13px", { "lineHeight": "18px", "letterSpacing": "0", "fontWeight": "400" }],
        "data-tabular": ["13px", { "lineHeight": "16px", "letterSpacing": "-0.01em", "fontWeight": "500" }]
      }
    },
  },
  plugins: [],
}
